<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net8.0-windows</TargetFramework>
    <AssemblyName>mouseTracker</AssemblyName>
    <RootNamespace>MouseTracker.App</RootNamespace>
    <ApplicationIcon>Assets\mouseTracker.ico</ApplicationIcon>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <UseWPF>true</UseWPF>
  </PropertyGroup>

  <ItemGroup>
    <Resource Include="Assets\mouseTracker.ico" />
  </ItemGroup>

</Project>
